apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-movie-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-movie-service
    spec:
      containers:
      - name: movie-service
        image: "{{ .Values.movie_service.image.repository }}:{{ .Values.movie_service.image.tag }}"
        ports:
        - containerPort: {{ .Values.movie_service.ports.http }}
        env:
        - name: DATABASE_URI
          value: "postgresql://{{ .Values.movie_db.env.POSTGRES_USER }}:{{ .Values.movie_db.env.POSTGRES_PASSWORD }}@{{ .Release.Name }}-movie-db/{{ .Values.movie_db.env.POSTGRES_DB }}"
        - name: CAST_SERVICE_HOST_URL
          value: "http://{{ .Release.Name }}-cast-service:8000/api/v1/casts/"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-movie-service
spec:
  selector:
    app: {{ .Release.Name }}-movie-service
  ports:
    - protocol: TCP
      port: 30080
      targetPort: {{ .Values.movie_service.ports.http }}
  type: NodePort
