apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-cast-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-cast-service
    spec:
      containers:
      - name: cast-service
        image: "{{ .Values.cast_service.image.repository }}:{{ .Values.cast_service.image.tag }}"
        ports:
        - containerPort: {{ .Values.cast_service.ports.http }}
        env:
        - name: DATABASE_URI
          value: "postgresql://{{ .Values.cast_db.env.POSTGRES_USER }}:{{ .Values.cast_db.env.POSTGRES_PASSWORD }}@{{ .Release.Name }}-cast-db/{{ .Values.cast_db.env.POSTGRES_DB }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cast-service
spec:
  selector:
    app: {{ .Release.Name }}-cast-service
  ports:
    - protocol: TCP
      port: 30081
      targetPort: {{ .Values.cast_service.ports.http }}
  type: NodePort
