apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-movie-db-pvc
spec:
  accessModes:
    - {{ default "ReadWriteOnce" $movieDb.persistence.accessMode }}
  resources:
    requests:
      storage: {{ default "1Gi" $movieDb.persistence.size }}
