apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-movie-db-pvc
spec:
  accessModes:
    - {{ $movieDb := default dict .Values.movie_db }}{{ default "ReadWriteOnce" $movieDb.persistence.accessMode }}
  resources:
    requests:
      storage: {{ $movieDb.persistence.size | default "1Gi" }}

