apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-movie-db-pvc
spec:
  accessModes:
    - {{ .Values.movie_db.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.movie_db.persistence.size }}
