apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-cast-db-pvc
spec:
  accessModes:
    - {{ $castDb := default dict .Values.cast_db }}{{ default "ReadWriteOnce" $castDb.persistence.accessMode }}
  resources:
    requests:
      storage: {{ $castDb.persistence.size | default "1Gi" }}
